apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadqxmz4403-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadqxmz4403-tenant-component
    app.kubernetes.io/part-of: loadqxmz4403-tenant-app
  name: loadqxmz4403-tenant-component
  namespace: loadqxmz4403-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadqxmz4403-tenant-component
    weight: null
status: {}
